"""
Dream State: compact, inspectable artifacts derived from REM dream output.

This module does not invent new dream content. It summarizes the dream
narratives already generated by REM replay so wake summaries can expose a
human-feeling but memory-grounded "morning brief".
"""
from __future__ import annotations

from collections import Counter
from typing import Any, Dict, Iterable, List


class DreamStateBuilder:
    """Build a deterministic Dream State artifact from REM dream records."""

    def build(
        self,
        dreams: List[Dict[str, Any]],
        tensions: List[Dict[str, Any]] | None = None,
        closed_threads: List[Dict[str, Any]] | None = None,
    ) -> Dict[str, Any]:
        if not dreams:
            state = self.empty()
            state["closed_threads"] = list(closed_threads or [])[:5]
            state["resolved_conflicts"] = [
                item.get("description", "")
                for item in state["closed_threads"]
                if item.get("description")
            ]
            return state

        tensions = tensions or []
        closed_threads = closed_threads or []
        replayed = self._collect_replayed_memories(dreams)
        tone = self._map_emotional_tone(
            dream.get("emotional_tone", "neutral") for dream in dreams
        )
        open_threads = self._collect_open_threads(replayed, tensions)

        if tensions:
            top = tensions[0]
            reason = ", ".join(top.get("signals", [])[:2]) or "unresolved signals"
            summary = (
                f"Sleep replay kept returning to {top.get('description')} "
                f"because it still looks unresolved ({reason})."
            )
        elif replayed:
            focus = self._join_preview(replayed[:3])
            summary = f"Sleep replay connected {focus}."
        else:
            summary = "Sleep replay did not surface a stable theme."

        return {
            "enabled": True,
            "dream_summary": summary,
            "dream_emotional_tone": tone,
            "replayed_memories": replayed[:8],
            "resolved_conflicts": [
                item.get("description", "")
                for item in closed_threads[:5]
                if item.get("description")
            ],
            "closed_threads": closed_threads[:5],
            "open_threads_for_today": open_threads[:3],
            "unresolved_tensions": tensions[:5],
            "dream_count": len(dreams),
        }

    @staticmethod
    def empty() -> Dict[str, Any]:
        return {
            "enabled": False,
            "dream_summary": "",
            "dream_emotional_tone": "neutral",
            "replayed_memories": [],
            "resolved_conflicts": [],
            "closed_threads": [],
            "open_threads_for_today": [],
            "unresolved_tensions": [],
            "dream_count": 0,
        }

    @staticmethod
    def _collect_replayed_memories(dreams: List[Dict[str, Any]]) -> List[str]:
        seen = set()
        memories: List[str] = []
        for dream in dreams:
            narrative = str(dream.get("narrative") or "")
            for part in narrative.split("|"):
                item = " ".join(part.strip().split())
                if not item or item.lower() == "unknown":
                    continue
                key = item.lower()
                if key in seen:
                    continue
                seen.add(key)
                memories.append(item)
        return memories

    @staticmethod
    def _map_emotional_tone(tones: Iterable[str]) -> str:
        counts = Counter(str(t or "neutral").lower() for t in tones)
        positive = counts.get("positive", 0)
        negative = counts.get("negative", 0)
        neutral = counts.get("neutral", 0)

        if positive and negative:
            return "conflicted"
        if negative > positive and negative >= neutral:
            return "anxious"
        if positive > negative and positive >= neutral:
            return "hopeful"
        return "calm"

    @staticmethod
    def _collect_open_threads(
        replayed_memories: List[str],
        tensions: List[Dict[str, Any]] | None = None,
    ) -> List[str]:
        threads: List[str] = []
        for tension in tensions or []:
            desc = str(tension.get("description") or "").strip()
            if desc and desc not in threads:
                threads.append(desc)

        markers = (
            "deadline",
            "conflict",
            "blocked",
            "stuck",
            "problem",
            "issue",
            "unclear",
            "todo",
            "next",
            "goal",
        )
        for memory in replayed_memories:
            lower = memory.lower()
            if any(marker in lower for marker in markers) and memory not in threads:
                threads.append(memory)
        return threads

    @staticmethod
    def _join_preview(items: List[str]) -> str:
        if len(items) == 1:
            return items[0]
        if len(items) == 2:
            return f"{items[0]} and {items[1]}"
        return f"{items[0]}, {items[1]}, and {items[2]}"
